[2024-11-13T02:30:08.635+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-13T02:30:08.744+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: PopulationDataToSnowflake.load_population_data scheduled__2024-11-12T02:30:00+00:00 [queued]>
[2024-11-13T02:30:08.771+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: PopulationDataToSnowflake.load_population_data scheduled__2024-11-12T02:30:00+00:00 [queued]>
[2024-11-13T02:30:08.778+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-13T02:30:08.818+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load_population_data> on 2024-11-12 02:30:00+00:00
[2024-11-13T02:30:08.857+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=676) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-13T02:30:08.863+0000] {standard_task_runner.py:63} INFO - Started process 688 to run task
[2024-11-13T02:30:08.866+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'PopulationDataToSnowflake', 'load_population_data', 'scheduled__2024-11-12T02:30:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/PopulationDataToSnowflake.py', '--cfg-path', '/tmp/tmpb9s0bz9g']
[2024-11-13T02:30:08.874+0000] {standard_task_runner.py:91} INFO - Job 13: Subtask load_population_data
[2024-11-13T02:30:09.249+0000] {task_command.py:426} INFO - Running <TaskInstance: PopulationDataToSnowflake.load_population_data scheduled__2024-11-12T02:30:00+00:00 [running]> on host e3260ad76193
[2024-11-13T02:30:11.486+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='PopulationDataToSnowflake' AIRFLOW_CTX_TASK_ID='load_population_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-12T02:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-12T02:30:00+00:00'
[2024-11-13T02:30:11.526+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-13T02:30:11.645+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-11-13T02:30:11.658+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.0, Python Version: 3.12.3, Platform: Linux-5.10.25-linuxkit-aarch64-with-glibc2.36
[2024-11-13T02:30:11.668+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-11-13T02:30:13.904+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-11-13T02:30:14.207+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-11-13T02:31:06.757+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-11-13T02:31:06.774+0000] {logging_mixin.py:188} INFO - Successfully loaded 100 rows into dev.raw_data.population_data
[2024-11-13T02:31:06.781+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-13T02:31:06.792+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-13T02:31:06.874+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=PopulationDataToSnowflake, task_id=load_population_data, run_id=scheduled__2024-11-12T02:30:00+00:00, execution_date=20241112T023000, start_date=20241113T023008, end_date=20241113T023106
[2024-11-13T02:31:07.014+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-13T02:31:07.060+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-13T02:31:07.062+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
