[2024-11-14T02:18:12.567+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-14T02:18:13.866+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stockprices_v2_decorator.extract manual__2024-11-14T02:17:52.411904+00:00 [queued]>
[2024-11-14T02:18:16.545+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stockprices_v2_decorator.extract manual__2024-11-14T02:17:52.411904+00:00 [queued]>
[2024-11-14T02:18:16.591+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-14T02:18:17.025+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): extract> on 2024-11-14 02:17:52.411904+00:00
[2024-11-14T02:18:17.276+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1852) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-14T02:18:17.488+0000] {standard_task_runner.py:63} INFO - Started process 1874 to run task
[2024-11-14T02:18:17.574+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'stockprices_v2_decorator', 'extract', 'manual__2024-11-14T02:17:52.411904+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/stockprices_v2_decorator(3).py', '--cfg-path', '/tmp/tmp7b1zx8ta']
[2024-11-14T02:18:17.630+0000] {standard_task_runner.py:91} INFO - Job 69: Subtask extract
[2024-11-14T02:18:22.445+0000] {task_command.py:426} INFO - Running <TaskInstance: stockprices_v2_decorator.extract manual__2024-11-14T02:17:52.411904+00:00 [running]> on host 3627cdc70e56
[2024-11-14T02:18:38.262+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stockprices_v2_decorator' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2024-11-14T02:17:52.411904+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-14T02:17:52.411904+00:00'
[2024-11-14T02:18:39.799+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-14T02:18:41.362+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-14T02:18:41.506+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stockprices_v2_decorator(3).py", line 37, in extract
    api_key = Variable.get('VANTAGE_API_KEY')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/variable.py", line 143, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable VANTAGE_API_KEY does not exist'
[2024-11-14T02:18:42.884+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=stockprices_v2_decorator, task_id=extract, run_id=manual__2024-11-14T02:17:52.411904+00:00, execution_date=20241114T021752, start_date=20241114T021814, end_date=20241114T021842
[2024-11-14T02:18:43.688+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 69 for task extract ('Variable VANTAGE_API_KEY does not exist'; 1874)
[2024-11-14T02:18:44.162+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-14T02:18:44.299+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
