[2024-11-14T03:43:16.590+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-14T03:43:16.614+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_run manual__2024-11-14T03:43:12.569937+00:00 [queued]>
[2024-11-14T03:43:16.627+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_run manual__2024-11-14T03:43:12.569937+00:00 [queued]>
[2024-11-14T03:43:16.628+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-14T03:43:16.647+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_run> on 2024-11-14 03:43:12.569937+00:00
[2024-11-14T03:43:16.661+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=3511) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-14T03:43:16.664+0000] {standard_task_runner.py:63} INFO - Started process 3513 to run task
[2024-11-14T03:43:16.664+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'BuildELT_dbt', 'dbt_run', 'manual__2024-11-14T03:43:12.569937+00:00', '--job-id', '183', '--raw', '--subdir', 'DAGS_FOLDER/build_elt_with_dbt.py', '--cfg-path', '/tmp/tmpzp1g3alt']
[2024-11-14T03:43:16.670+0000] {standard_task_runner.py:91} INFO - Job 183: Subtask dbt_run
[2024-11-14T03:43:16.734+0000] {task_command.py:426} INFO - Running <TaskInstance: BuildELT_dbt.dbt_run manual__2024-11-14T03:43:12.569937+00:00 [running]> on host 3627cdc70e56
[2024-11-14T03:43:16.833+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='BuildELT_dbt' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2024-11-14T03:43:12.569937+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-14T03:43:12.569937+00:00'
[2024-11-14T03:43:16.837+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-14T03:43:16.843+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-14T03:43:16.845+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt run --profiles-dir /opt/***/build_dbt --project-dir /opt/***/build_dbt']
[2024-11-14T03:43:16.871+0000] {subprocess.py:86} INFO - Output:
[2024-11-14T03:43:19.014+0000] {subprocess.py:93} INFO - [0m03:43:19  Running with dbt=1.8.7
[2024-11-14T03:43:19.740+0000] {subprocess.py:93} INFO - [0m03:43:19  Registered adapter: snowflake=1.8.4
[2024-11-14T03:43:20.062+0000] {subprocess.py:93} INFO - [0m03:43:20  Encountered an error:
[2024-11-14T03:43:20.064+0000] {subprocess.py:93} INFO - Parsing Error
[2024-11-14T03:43:20.065+0000] {subprocess.py:93} INFO -   at path []: Snapshots must be configured with a 'strategy', 'unique_key', and 'target_schema'.
[2024-11-14T03:43:20.794+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2024-11-14T03:43:20.800+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-14T03:43:20.834+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2024-11-14T03:43:20.844+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=BuildELT_dbt, task_id=dbt_run, run_id=manual__2024-11-14T03:43:12.569937+00:00, execution_date=20241114T034312, start_date=20241114T034316, end_date=20241114T034320
[2024-11-14T03:43:20.875+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 183 for task dbt_run (Bash command failed. The command returned a non-zero exit code 2.; 3513)
[2024-11-14T03:43:20.936+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-14T03:43:20.982+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-14T03:43:20.990+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
