[2024-11-14T02:29:29.871+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-14T02:29:29.907+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stockprices_v2_decorator.extract manual__2024-11-14T02:24:14.208059+00:00 [queued]>
[2024-11-14T02:29:29.917+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stockprices_v2_decorator.extract manual__2024-11-14T02:24:14.208059+00:00 [queued]>
[2024-11-14T02:29:29.919+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-11-14T02:29:29.941+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): extract> on 2024-11-14 02:24:14.208059+00:00
[2024-11-14T02:29:29.955+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2096) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-14T02:29:29.958+0000] {standard_task_runner.py:63} INFO - Started process 2100 to run task
[2024-11-14T02:29:29.968+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'stockprices_v2_decorator', 'extract', 'manual__2024-11-14T02:24:14.208059+00:00', '--job-id', '95', '--raw', '--subdir', 'DAGS_FOLDER/stockprices_v2_decorator(3).py', '--cfg-path', '/tmp/tmp8oo0m2gn']
[2024-11-14T02:29:29.972+0000] {standard_task_runner.py:91} INFO - Job 95: Subtask extract
[2024-11-14T02:29:30.025+0000] {task_command.py:426} INFO - Running <TaskInstance: stockprices_v2_decorator.extract manual__2024-11-14T02:24:14.208059+00:00 [running]> on host 3627cdc70e56
[2024-11-14T02:29:30.222+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stockprices_v2_decorator' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2024-11-14T02:24:14.208059+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-14T02:24:14.208059+00:00'
[2024-11-14T02:29:30.231+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-14T02:29:30.263+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-14T02:29:30.265+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/stockprices_v2_decorator(3).py", line 39, in extract
    url = url_template.format(symbol=symbol, vantage_api_key=api_key)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: ' vantage_api_key'
[2024-11-14T02:29:30.289+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=stockprices_v2_decorator, task_id=extract, run_id=manual__2024-11-14T02:24:14.208059+00:00, execution_date=20241114T022414, start_date=20241114T022929, end_date=20241114T022930
[2024-11-14T02:29:30.303+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 95 for task extract (' vantage_api_key'; 2100)
[2024-11-14T02:29:30.338+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-11-14T02:29:30.365+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
