[2024-11-13T19:36:12.179+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-13T19:36:12.209+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_test manual__2024-11-13T19:35:50.620919+00:00 [queued]>
[2024-11-13T19:36:12.222+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: BuildELT_dbt.dbt_test manual__2024-11-13T19:35:50.620919+00:00 [queued]>
[2024-11-13T19:36:12.229+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-11-13T19:36:12.245+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_test> on 2024-11-13 19:35:50.620919+00:00
[2024-11-13T19:36:12.263+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1879) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-13T19:36:12.267+0000] {standard_task_runner.py:63} INFO - Started process 1881 to run task
[2024-11-13T19:36:12.268+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'BuildELT_dbt', 'dbt_test', 'manual__2024-11-13T19:35:50.620919+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/build_elt_with_dbt.py', '--cfg-path', '/tmp/tmp61skf7v6']
[2024-11-13T19:36:12.280+0000] {standard_task_runner.py:91} INFO - Job 25: Subtask dbt_test
[2024-11-13T19:36:12.361+0000] {task_command.py:426} INFO - Running <TaskInstance: BuildELT_dbt.dbt_test manual__2024-11-13T19:35:50.620919+00:00 [running]> on host 3627cdc70e56
[2024-11-13T19:36:12.462+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='BuildELT_dbt' AIRFLOW_CTX_TASK_ID='dbt_test' AIRFLOW_CTX_EXECUTION_DATE='2024-11-13T19:35:50.620919+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-13T19:35:50.620919+00:00'
[2024-11-13T19:36:12.466+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-13T19:36:12.469+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-11-13T19:36:12.470+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt test --profiles-dir /opt/***/build_dbt --project-dir /opt/***/build_dbt']
[2024-11-13T19:36:12.491+0000] {subprocess.py:86} INFO - Output:
[2024-11-13T19:36:13.922+0000] {subprocess.py:93} INFO - [0m19:36:13  Running with dbt=1.8.7
[2024-11-13T19:36:14.848+0000] {subprocess.py:93} INFO - [0m19:36:14  Registered adapter: snowflake=1.8.4
[2024-11-13T19:36:15.001+0000] {subprocess.py:93} INFO - [0m19:36:15  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2024-11-13T19:36:15.004+0000] {subprocess.py:93} INFO - There are 1 unused configuration paths:
[2024-11-13T19:36:15.004+0000] {subprocess.py:93} INFO - - models.build_dbt.example
[2024-11-13T19:36:15.337+0000] {subprocess.py:93} INFO - [0m19:36:15  Found 5 models, 2 sources, 459 macros
[2024-11-13T19:36:15.344+0000] {subprocess.py:93} INFO - [0m19:36:15
[2024-11-13T19:36:15.347+0000] {subprocess.py:93} INFO - [0m19:36:15  Nothing to do. Try checking your model configs and model specification args
[2024-11-13T19:36:16.425+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-11-13T19:36:16.433+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-13T19:36:16.481+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=BuildELT_dbt, task_id=dbt_test, run_id=manual__2024-11-13T19:35:50.620919+00:00, execution_date=20241113T193550, start_date=20241113T193612, end_date=20241113T193616
[2024-11-13T19:36:16.555+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-11-13T19:36:16.599+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-13T19:36:16.602+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
